application: webaudiokitchen
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: index.html
  
#- url: /(.*\.(appcache|manifest))
#  static_files: \1
#  mime_type: text/cache-manifest
#  upload: (.*\.(appcache|manifest))
#  expiration: 1s
  
- url: /res
  static_dir: res
  
- url: /js
  static_dir: js
  
- url: /py/mail.py
  script: py/mail.py